site_name: Bardos do Mondego
site_description: Wiki colaborativa para a campanha West Marches em Greyhawk
site_author: Serelith

docs_dir: docs
site_dir: site

nav:
  - In√≠cio: index.md
  - üåÜ Locais Principais:
      - Free City of Greyhawk: mapa_da_cidade_de_greyhawk.md
      - The Company: the_company.md
      - Ruin Sites Index: ruin_sites_index.md
  - üèôÔ∏è Bairros da Cidade:
      - High Quarter: high_quarter.md
      - Garden Quarter: garden_quarter.md
      - University Quarter: university_quarter.md
      - River Quarter: river_quarter.md
      - Thieves‚Äô Quarter: thieves_quarter.md
      - Artisans‚Äô Quarter: artisans_quarter.md
      - Foreign Quarter: foreign_quarter.md
      - City Market: city_market.md
      - Slum Quarter: slum_quarter.md
  - üõê Locais e Estruturas:
      - Templo de Oghma: templo_de_oghma.md
      - Grande Biblioteca: grande_biblioteca.md
      - Universidade Arcana: universidade_arcana.md
      - Estalagem da Companhia: estalagem_da_companhia.md
      - Rua do Drag√£o Enferrujado: rua_do_dragao_enferrujado.md
  - üë• NPCs em Destaque:
      - Lord Aleister Devraine: lord_aleister_devraine.md
      - Sister Blathine: sister_blathine.md
      - Mistress Lyral Quil: mistress_lyra_quil.md
      - Tomtha Beaknose: tomtha_beaknose.md
      - Iquander: iquander.md
      - Jandel the Lintwatcher: jandel_the_lintwatcher.md
      - Talandra Valaxar: talandra_valaxar.md
      - Wenla Frott: wenla_frott.md
      
  - üìú DM:
      - üß≠ Aventuras:
          - Bullet Points Sess√µes 1-10: dm/aventuras/summary/bullet_points_1-10.md    
          - Os Fungos do Bosque: dm/aventuras/summary/s01_os_fungos_do_bosque_summary.md
          - Dificuldades na Mina de Obsidiana: dm/aventuras/summary/s02_dificuldades_na_mina_de_obsidiana_summary.md
          - Emboscada nas Margens do Rio Neem: dm/aventuras/summary/s03_emboscada_nas_margens_do_rio_neem_summary.md
          - Vale do Vento Sombrio: dm/aventuras/summary/s03_vale_do_vento_sombrio_summary.md
          - Regresso √† Mina, Gravuras: dm/aventuras/summary/s04_regresso_mina_gravuras_summary.md
          - Two Fords, Doen√ßa do Rio e o Moinho: dm/aventuras/summary/s04_two_fords_doenca_moinho_summary.md
          - Vale do Vento Sombrio, Drag√£o: dm/aventuras/summary/s04_vale_do_vento_sombrio_dragao_summary.md
          - Acampamento Goblin e Resgate: dm/aventuras/summary/s05_acampamento_goblin_caravana_resgate_summary.md
          - As M√°scaras da Morte (Mistwood): dm/aventuras/summary/s05_as_mascaras_da_morte_mistwood_summary.md
          - Di√°rio da Ac√≥lita Morvanya: dm/aventuras/summary/s05_diario_acolita_morvanya_summary.md
          - Bullywugs e Basilisco: dm/aventuras/summary/s08_bullywugs_e_basilisco_summary.md
          - As Tr√™s Pedras e o Ritual: dm/aventuras/summary/s08_as_tres_pedras_e_o_ritual_summary.md
          - Roubo e Persegui√ß√£o das Pedras: dm/aventuras/summary/s08_roubo_e_perseguicao_das_pedras_summary.md
          - Nave Illithid e Entrega de Thoren: dm/aventuras/summary/s08_nave_illithid_e_entrega_de_thoren_summary.md
          - Lago Umbra, O Cavaleiro e as Sombras: dm/aventuras/summary/s08_lago_umbra_cavaleiro_sombras_summary.md
          - Eribend, Raptos & Cultistas de Odrak: dm/aventuras/summary/s07_eribend_raptos_cultistas_odrak_summary.md
          - Terceiro Templo, Basilisco & Feixe de Luz: dm/aventuras/summary/s07_terceiro_templo_basilisco_pedras_luz_summary.md
          - Mist√©rio de High Ery: dm/aventuras/summary/s09_misterio_de_high_ery_summary.md
          - Entrega para Blackfair Manor: dm/aventuras/summary/s09_entrega_para_blackfair_manor_summary.md
          - Baile dos High Fae: dm/aventuras/summary/s09_baile_dos_high_fae_summary.md
          - Sangue e Ouro no P√¢ntano: dm/aventuras/summary/s10_a_rota_da_cia_sangue_e_ouro_no_pantano_summary.md
          - O Segredo de Peculiar Manor: dm/aventuras/summary/s10_o_segredo_de_peculiar_manor_summary.md
          - Sombras de Iuz: dm/aventuras/summary/s10_sombras_de_iuz_summary.md
          - Sombras sobre Erybend: dm/aventuras/summary/s10_sombras_sobre_erybend_summary.md   
          - O Legado de Krixis, o Valente: dm/aventuras/summary/s11_o_legado_de_krixis_summary.md  
          - Pris√£o e Reden√ß√£o de Dustin: dm/aventuras/summary/s11_prisao_e_redencao_summary.md 
          - Companhia das Tr√™s Pedras: dm/aventuras/summary/s11_trilogia_tres_pedras_mindflayer_summary.md 
          - ris√£o e Resgate de Dustin: dm/aventuras/summary/s12_prisao_e_resgate_de_dustin_summary.md
          - Dandan e os 40 Kobolds: dm/aventuras/summary/s13_dandan_e_os_40_kobolds_summary.md           
          - Enfrentando a Guilda dos Ladr√µes: dm/aventuras/summary/s13_enfrentando_a_guilda_dos_ladroes_summary.md 
          - Investigar o Sul da Cidade de Greyhawk: dm/aventuras/summary/s13_investigar_o_sul_da_cidade_de_greyhawk_summary.md
          - O Inc√™ndio Misterioso: dm/aventuras/summary/s13_o_incendio_misterioso_summary.md
          - O Iue Nos Espera a Nova Cidade: dm/aventuras/summary/s13_o_que_nos_espera_a_nova_cidade_summary.md           
      - üìú SESS√ïES:
          - S01 - 2025-01-02: dm/s01_-_2025-01-02.md
          - S02 - 2025-01-09: dm/s02_-_2025-01-09.md
          - S03 - 2025-01-15: dm/s03_-_2025-01-15.md
          - S04 - 2025-01-23: dm/s04_-_2025-01-23.md
          - S05 - 2025-01-30: dm/s05_-_2025-01-30.md
          - S06 - 2025-02-13: dm/s06_-_2025-02-13.md
          - S07 - 2025-02-20: dm/s07_-_2025-02-20.md
          - S08 - 2025-02-27: dm/s08_-_2025-02-27.md
          - S09 - 2025-03-06: dm/s09_-_2025-03-06.md
          - S10 - 2025-03-13: dm/s10_-_2025-03-13.md
          - S11 - 2025-03-20: dm/s11_-_2025-03-20.md
          - S12 - 2025-03-27: dm/s12_-_2025-03-27.md
          - S13 - 2025-04-03: dm/s13_-_2025-04-03.md
          - S14 - 2025-04-10: dm/s14_-_2025-04-10.md
          - S16 - 2025-04-24: dm/s16_-_2025-04-24.md
          - S22 - 2025-06-05: dm/s22_-_2025-06-05.md
          - S27 - 2025-07-10: dm/s27_-_2025-07-10.md
          - S28 - 2025-07-17: dm/s28_-_2025-07-17.md
          - S29 - 2025-07-24: dm/s29_-_2025-07-24.md
      - üßë‚Äçüé≤ PCs:
          - Arkos Vasell: dm/pc/pc_arkos_vasell.md
          - Asinius: dm/pc/pc_asinius.md
          - Aurora: dm/pc/pc_aurora.md
          - Bok Thunderfist: dm/pc/pc_bok_thunderfist.md
          - Conan: dm/pc/pc_conan_barbaro_ra.md
          - Danda: dm/pc/pc_dandan.md
          - Draven: dm/pc/pc_draven.md
          - Drayl Barash: dm/pc/pc_drayl_barash.md
          - Dustin Thorne: dm/pc/pc_dustin_thorne.md
          - Eirwen: dm/pc/pc_eirwen.md
          - Eldric Silvanus: dm/pc/pc_eldric_silvanus.md
          - Endovan Bom Sossego: dm/pc/pc_endovan_bomsossego.md
          - Flynn: dm/pc/pc_flynn.md
          - Friedrick ‚ÄòFreddy‚Äô Junsi: dm/pc/pc_friedrick_junsi.md
          - Gauthak: dm/pc/pc_gauthak.md
          - Grix‚Äômolah: dm/pc/pc_grixmolah.md
          - Kai: dm/pc/pc_kai.md
          - Ketrich Flavifer: dm/pc/pc_ketrich_flavifer.md
          - Leo: dm/pc/pc_leo.md
          - Lia: dm/pc/pc_lia.md 
          - Lirael: dm/pc/pc_lirael.md  
          - Lone Straw: dm/pc/pc_lone_straw.md
          - Lucian Vyrolyn: dm/pc/pc_lucian_vyrolyn.md
          - Lucien: dm/pc/pc_lucien.md
          - Orianna: dm/pc/pc_orianna.md
          - Markus Grimm: dm/pc/pc_markus_grimm.md
          - Raylahn: dm/pc/pc_raylahn.md
          - Redvel: dm/pc/pc_redvel.md
          - Sarvien Midlor: dm/pc/pc_sarvian_midlor.md
          - Selene: dm/pc/pc_selene.md
          - Silfir: dm/pc/pc_silfir.md
          - Tabasco de Lumeiros: dm/pc/pc_tabasco_de_lumeiros.md
          - Thoren: dm/pc/pcpc_thoren.md
          - Triss Merill: dm/pc/pc_triss_merill.md
          - Ulma: dm/pc/pc_ulma.md
          - Usopp: dm/pc/pc_usopp.md
          - Ustrax: dm/pc/pc_ustrax.md
          - Vaunia: dm/pc/pc_vaunia.md
          - Varus / Zeldris: dm/pc/pc_varus_zeldris.md
          - Wagner: dm/pc/pc_wagner.md
          - Wandering Sage: dm/pc/pc_wandering_sage.md
          - Zahel: dm/pc/pc_zahel.md
      - üìç Localiza√ß√µes:
          - Taverna / The Tavern: dm/taverna.md
          - Cidade de Greyhawk / Free City of Greyhawk: dm/cidade_de_greyhawk.md
          - Garden Quarter / Bairro dos Jardins: dm/garden_quarter.md
          - Museu das Maravilhas Naturais e Arcanas de Greyhawk / Museum of Natural & Arcane Wonders of Greyhawk: dm/museu_das_maravilhas.md
          - Vale de Lytharien / Lytharien Vale: dm/vale_de_lytharien.md
          - Castelo Ruina-de-Ebano / Ebony-Ruin Castle: dm/castelo_ruina_de_ebano.md
          - Vila de Pessegueiro / Peach Village: dm/vila_de_pessegueiro.md
          - Esgotos de Greyhawk / Greyhawk Sewers: dm/esgotos_de_greyhawk.md
          - Taberna da Trixie / Trixie‚Äôs Tavern: dm/taberna_da_trixie.md
          - Taberna do Drag√£o Dourado / Golden Dragon‚Äôs Tavern: dm/golden_dragon_tavern.md
          - Sapol√¢ndia / Frog Village: dm/sapolandia.md
          - Altar de Celestia / Altar of Celestia: dm/altar_de_celestia.md
          - Nave Espacial dos Illithids / Mind Flayer Spaceship: dm/nave_illithid.md
          - Nave-M√£e dos Illithids / Illithid Mothership: dm/nave_mae_illithid.md
          - Templo Abandonado dos Kobolds / Abandoned Kobold Temple: dm/templo_abandonado_kobold.md
          - Fonte do Garden Quarter / Garden Quarter Fountain: dm/garden_quarter_fountain.md
          - Galeria das Bestas / Gallery of Beasts (Museum): dm/galeria_das_bestas.md
          - Galeria dos Lamentos / Gallery of Laments (Museum): dm/galeria_dos_lamentos.md
          - Sala Subterr√¢nea dos Frascos / Underground Room of Flasks (Museum): dm/sala_subterranea_frascos.md
          - Laborat√≥rio do Curador / Curator‚Äôs Laboratory (Museum): dm/laboratorio_do_curador.md
          - Outros Distritos de Greyhawk / Other Districts of Greyhawk: dm/outros_distritos_greyhawk.md
      - üó∫Ô∏è Outras Localiza√ß√µes:
          - Casa dos Greenbottle: dm/casa_dos_greenbottle.md
          - Caverna das L√°grimas de Cristal: dm/caverna_das_lagrimas_de_cristal.md
          - Caverna dos Dois Postes: dm/caverna_dos_dois_postes.md
          - Caverna Submersa: dm/caverna_submersa.md
          - Cripta das Sombras: dm/cripta_das_sombras.md
          - Eribend: dm/eribend.md
          - Ilha da Lua Negra: dm/ilha_da_lua_negra.md
          - Jardim de Greyhawk (Garden Quarter): dm/jardim_greyhawk.md
          - Lago Umbra: dm/lago_umbra.md
          - Loja Olho de Boccob: dm/loja_olho_de_boccob.md
          - Mirens Hallow: dm/mirens_hallow.md
          - Museu das Maravilhas Naturais e Arcanas de Greyhawk: dm/museu_das_maravilhas_naturais_e_arcanas_de_greyhawk.md
          - Parque da Cidade: dm/parque_da_cidade.md
          - Ru√≠nas das Sombras: dm/ruinas_das_sombras.md
          - Ru√≠nas do Forte da Casa Vanthir: dm/ruinas_do_forte_da_casa_vanthir.md
          - Taberna Machado Quebrado: dm/taberna_machado_quebrado.md
          - Taberna Sombra de √Ågua: dm/taberna_sombra_de_agua.md
          - Taberna The Golden Dragon‚Äôs Tavern: dm/taberna_golden_dragon.md
          - Templo da Ordem de Scarlat: dm/templo_ordem_de_scarlat.md
          - Torre do Eclipse: dm/torre_do_eclipse.md
          - Vale de Lytharien: dm/vale_de_lytharien.md
          - Vila de Pessegueiro: dm/vila_de_pessegueiro.md
          - Vila de Vauria: dm/vila_de_vauria.md  
      - üë• NPCs:
          - Alto-Inquisidor Malrik Dorn: dm/malrik_dorn.md
          - Aria Greenbottle: dm/aria_greenbottle.md
          - Bareth Lionmane: dm/bareth_lionmane.md
          - Bartleby Quick: dm/bartleby_quick.md
          - Borogrove: dm/borogrove.md
          - Brand Orvain: dm/brand_orvain.md
          - Brandon Bane: dm/brandon_bane.md
          - Branwir: dm/branwir.md
          - Calra Brightwater: dm/calra_brightwater.md
          - Cleseur: dm/cleseur.md
          - Curador: dm/curador.md
          - Darsen: dm/darsen.md
          - Dolrea Vas: dm/dolrea_vas.md
          - Druida Infetado: dm/druida_infestado.md
          - Eliza Greenbottle: dm/eliza_greenbottle.md
          - Finn Greenbottle: dm/finn_greenbottle.md
          - Garruk Valstein: dm/garruk_valstein.md
          - Guarda da Cidade: dm/guarda_da_cidade.md
          - Jeraldina: dm/jeraldina.md
          - Liwana: dm/liwana.md
          - Luthor Greystone: dm/luthor_greystone.md
          - Major-domo do Castelo: dm/majordomo_castelo.md
          - Marielle Duns: dm/marielle_duns.md
          - Mestre Donlan: dm/mestre_donlan.md
          - Mestre Tolinn: dm/mestre_tolinn.md
          - Mestre Tolyn: dm/mestre_tolyn.md
          - M√≠mico / The Mimic Prince: dm/mimico.md
          - Mr. 0: dm/mr0.md
          - Myria: dm/myria.md
          - Old Rasko: dm/old_rasko.md
          - Outros NPCs: dm/outros_npcs.md
          - Prysanna: dm/prysanna.md
          - Pryssana: dm/pryssana.md
          - Raveth Xil‚ÄôZyrl: dm/raveth_xil_zyrl.md
          - Senhor Rodrik: dm/senhor_rodrik.md
          - Snikil Pescabrasa: dm/snikil_pescabrasa.md
          - Soren Vest: dm/soren_vest.md
          - Sybel Astren: dm/sybel_astren.md
          - Taverneiro do Ref√∫gio: dm/taverneiro_refugio.md
          - Thamior: dm/thamior.md
          - Tilda Auren: dm/tilda_auren.md
          - Tobias Greenbottle: dm/tobias_greenbottle.md
          - Trixie: dm/trixie.md
          - Vareth Lionmane: dm/vareth_lionmane.md
          - Vellira: dm/vellira.md
          - Verena Kestrel: dm/verena_kestrel.md
          - Zael: dm/zael.md
          - Zavros Karamark: dm/zavros_karamark.md
          - Zeibranth: dm/zeibranth.md              
      - üê≤ Monstros:
          - Armadura Animada / Animated Armor: dm/armadura_animada.md
          - Ghast: dm/ghast.md
          - Ghoul: dm/ghoul.md
          - Zombie / Zumbi: dm/zombie.md
          - Criatura das Sombras / Shadow Creature: dm/criatura_das_sombras.md
          - Espectro / Spectral Wraith: dm/spectral_wraith.md
          - Illithid (Mind Flayer): dm/illithid.md
          - Kobold: dm/kobold.md
          - Enxame de Morcegos / Bat Swarm: dm/enxame_de_morcegos.md
          - Enxame de Ratos / Swarm of Rats: dm/enxame_de_ratos.md
          - Pirata / Pirate: dm/pirata.md
          - Criatura Abissal / Abyssal Creature: dm/criatura_abissal.md
          - Sombra / Shadow: dm/sombra.md
          - Guardi√£o da Caverna / Cave Guardian: dm/guardian_da_caverna.md
          - Monstro da Lagoa / Lagoon Monster: dm/monstro_da_lagoa.md
          - Serpente Gigante / Giant Serpent: dm/serpente_gigante.md
          - Wight: dm/wight.md
          - Unic√≥rnio Lend√°rio / Legendary Unicorn: dm/unic√≥rnio_lendario.md
          - Criatura de N√©voa / Mist Creature: dm/criatura_de_nevoa.md
          - Cultista / Cultist: dm/cultista.md
          - Elemental de Fogo / Fire Elemental: dm/elemental_de_fogo.md
          - Corvo Gigante / Giant Crow: dm/corvo_gigante.md
      - üè∑Ô∏è Organiza√ß√µes & Rumores:
          - Organiza√ß√µes:
              - Conclave Anf√≠bio: dm/conclave_anfibio.md
              - Guilda dos Assassinos: dm/guilda_dos_assassinos.md
              - Guilda dos Ladr√µes: dm/guilda_dos_ladroes.md
              - Ordem de Scarlat: dm/ordem_de_scarlat.md
              - Sociedade dos Magos: dm/sociedade_dos_magos.md
          - Rumores:
              - Boatos sobre Piratas em Greyhawk: dm/boatos_sobre_piratas.md
              - Lendas das Ru√≠nas das Sombras: dm/lendas_das_ruinas_sombras.md
              - Rumores da M√£o Roubada: dm/rumores_da_mao_roubada.md
              - Rumores do Vale de Lytharien: dm/rumores_do_vale_lytharien.md
              - Rumores sobre Illithids: dm/rumores_sobre_illithids.md
      - üíé Loot & Itens M√°gicos:
          - Anel M√°gico de Zorg: dm/anel_magico_de_zorg.md
          - Bra√ßadeiras de Defesa: dm/bracers_of_defense.md
          - Capa da Neblina: dm/capa_da_neblina.md
          - Espada +1: dm/espada_mais_um.md
          - Espada da Luz Velada: dm/espada_luz_velada.md
          - Gema das Cinco Vozes: dm/gema_das_cinco_vozes.md
          - Manto da Sombra Viva: dm/manto_sombra_viva.md
          - Medalh√£o do Sussurro: dm/medalhao_do_sussurro.md
          - Pergaminho de Expulsar Mortos-Vivos: dm/pergaminho_expulsar_mortos_vivos.md
          - Po√ß√£o da Esperan√ßa: dm/pocao_da_esperanca.md
          - Po√ß√£o de Resist√™ncia a Necr√≥tico: dm/pocao_resistencia_necrotico.md
          - Rel√≠quia Amaldi√ßoada: dm/reliquia_amaldicoada.md

theme:
  name: material
  language: pt
  palette:
    primary: black
    accent: indigo

use_directory_urls: true

plugins:
  - search